### ISSUE TITLE
allOf with object schemas and additionalProperties = false

### ISSUE THREAD

**Issue by dawidcha** [json-schema/json-schema#116] opened 2014-02-11 22:12 UTC
As I understand, the pattern for reusing base schema definitions across multiple schemas is to use 'allOf' to include base schema that we're mixing in.  If this is to validate successfully, all such base schemas must have additionalProperties set to false (or omitted) which means that they, and the derived schema have no way of limiting the allowed property set.

Since I can't actually think of any cases when using allOf on several object schemas with additionalProperties set to false would make any sense, I'd like to propose that the draft spec be updated to say that when using allOf with object schemas, the additionalProperties setting will be treated as 'true', for the purposes of validation, but if all schemas in the allOf list actually have additionalProperties set to false then the derived schema will inherit that setting.

Did that make any sense?

**Comment by wking** [comment] 2015-01-08 17:30
Any progress on this?  `propertiesFrom` sounds fine to me, as does special `additionalProperties` handling for `allOf` (using something like the [ban unknown properties][bup] semantics when any schema in the `allOf` has `additionalProperties` set to `false`).

[bup]: https://github.com/json-schema/json-schema/wiki/ban-unknown-properties-mode-%28v5-proposal%29

**Comment by fge** [comment] 2015-01-08 20:10
@wking well, since then I have taken another route; and I strongly disagree with the "ban unknown properties" mode, it's a hack (note that it cannot be enforced at the schema level).

My proposal is instead to implement schema patching via either "$merge" or "$patch"; please see the Google group for more information, I have posted threads recently about this.

**Comment by wking** [comment] 2015-01-08 20:22
On Thu, Jan 08, 2015 at 12:10:39PM -0800, Francis Galiegue wrote:
> My proposal is instead to implement schema patching via either
> "$merge" or "$patch"; please see the Google group for more
> information, I have posted threads recently about this.

Links to recent threads about $merge and $patch:

* How is the proposal for $merge and $patch going? [1]
* Status of $merge and $patch, please [2].
* $patch and $merge, an explanation -- plus strictProperties [3].

[1]: https://groups.google.com/forum/#!topic/json-schema/q76-qqJHIaM
[2]: https://groups.google.com/forum/#!topic/json-schema/rH_O7KAEX8A
[3]: https://groups.google.com/forum/#!topic/json-schema/sztyQoNlnDM

**Comment by wking** [comment] 2015-01-08 20:30
And the thread kicking off $merge and $patch seems to be [1], although
I'm not sure why it moved to the mailing list from here ;).

[1]: https://groups.google.com/d/topic/json-schema/mmPVym3Pfig/discussion

**Comment by JulienPalard** [comment] 2015-06-05 13:48
I just got hit by this problem and I'm not a big fan of trying to stick on `allOf` nor the `"merge": {"source": ..., "with: ...}`.

First: `allOf` seems semantically false, we're clearly not requiering "all of the given schema" to be true as it's impossible due to their "additionalProperties", and I'm against "adding an if to cope with this".

Second: I first though of merge before reading the mailing list, but this way:

```
"merge": [
    { "$ref": "schema1" },
    { "$ref": "schema2" }
]
```

This way we'll be able to merge more than two schemas, which may have a usage.

Also it looks a lot like:

```
{
"array": {
    "items": [
        { "$ref": "schema1" },
        { "$ref": "schema2" }
        ]
    }
}
```

but clear / explicit / readable (I personally, as a newcomer of jsonschema, don't understand why the "array / item" would do the trick for now, I'll have to read the doc again ^-^)

**Comment by epoberezkin** [comment] 2016-02-23 22:02
@dawidcha I agree that the current definition of additionalProperties in the standard causes a considerable confusion. See for example this [recent issue](https://github.com/epoberezkin/ajv/issues/129) about it. The problem is that we try to assign language semantics to the rules that are defined in a very strict, shallow way (i.e. not affected by anything but siblings) and doing so we confuse ourselves.

I nevertheless think that bending the standard to solve the confusion problem is an absolutely terrible idea. There are a lot of applications and schemas relying on this strictly defined behaviour, regardless how intuitive it is, and making the same keywords mean different things in the next version of the standard will make migration very difficult for a lot of people. So I think all currently defined keywords should keep their meaning and the confusion problem should be solved with education - there are plenty of materials around. I think even removing keywords is a bad idea, but changing them is just terrible...

We can extend the standard to allow it to solve the problems that currently are difficult to solve. I think "unknown" properties concept proposed by @geraintluff can be a good idea, although I am yet to see the case where the schema cannot be refactored to achieve what you want to achieve without it. At the same time, refactoring often hides the meaning of the schema which is not a good thing.

I agree with @fge that this is the "mode of validation" rather than the part of the schema makes it a bit strange and almost out of the scope of the standard. I think we could introduce the keyword "unknownProperties" that can be only boolean (no need to make it accept the schema I think :), that would take into account all properties defined in properties/patternProperties/patternGroups both on the same level and in all subschemas in allOf, anyOf, oneOf and maybe even "not" and "switch" keywords.

That downside is that this approach would require to use this keyword on all levels where such restriction is necessary. The upside is that it would allow flexibility, while validation mode won't. Validators still could implement it as the mode, as z-schema did with additionalProperties and many other keywords. But it would be outside of the standard.

The complexity comes from the question what to do with properties defined in $refs that are used inside allOf etc. @geraintluff, does your current implementation of "unknown properties" take properties from refs into account? What if they are recursive?

So all this complexity makes me love the current shallowness of the standard and holds me back from implementing unknown properties in Ajv

**Comment by fge** [comment] 2016-02-23 23:58
OK, I am not an active member of the process anymore, but might I just mention that my patch proposal would just solve all of these miseries?

**Comment by epoberezkin** [comment] 2016-02-24 00:10
I missed those ideas. It works I think, can probably be simpler.

**Comment by j-funk** [comment] 2016-04-14 20:47
+1 for `propertiesFrom` solution proposed by @fge above.

**Comment by handrews** [comment] 2016-10-23 00:28
@dawidcha 
This repository has been deprecated, could you please close this issue (none of us have permissions for it anymore).

There has been further discussion of this general topic here: https://groups.google.com/forum/#!forum/json-schema

You can join the current work at https://github.com/json-schema-org/json-schema-spec if you'd like to continue discussing this.

**Closed** 2016-12-29 20:39 UTC
